jwt_secret: a_very_long_and_secure_jwt_secret_for_testing

theme: light
server:
  host: 0.0.0.0
  port: 9091
  disable_healthcheck: true

log:
  level: debug

totp:
  issuer: authelia.com

authentication_backend:
  file:
    path: /config/users_database.yml

access_control:
  default_policy: one_factor

session:
  secret: insecure_session_secret
  domain: localhost

storage:
  encryption_key: a_very_long_and_secure_encryption_key_for_testing
  local:
    path: /config/db.sqlite3

notifier:
  filesystem:
    filename: /config/notification.txt



identity_providers:
  oidc:
    hmac_secret: insecure_hmac_secret_that_is_at_least_thirty_two_bytes_long
    issuer_private_key: |
      -----BEGIN PRIVATE KEY-----
      MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDX8pgHWzuJlj8U
      rCs3lWVpAMXKH8r1IFIKWK6dbH9J2vSkcOKz3yTqTWCIztG1pqI1+fxqIfs21p7Z
      7zwB4G5JS0TP7MWOJBPv5dcAprnpERHz2kCgQ4ckCzOmE+8CfQewbCvJGPHO3iXw
      tWQYAC6Ac5p+Uz3sJZAJhDtwUU0PXQFtNUNJdy9b5tojTU9j0/s4WNM5m29Ej998
      IULlu1epLi/Rgdu5vgxjWiW+Xscfofron4raADHjgqn0FJ21umsFpP0Ed9CGR6E3
      UxPjrXrqdFfMkG+E/EDyQkEH/xowgceilcewAcGNXWDI9KYKxewsZv70og8NKUNm
      cBAuzJ89AgMBAAECggEAN+uXWNhUO5XPsf+/lT43q5BKp8PB3+ZFuG4skZGGCM8N
      aQPegOu4+H+fDu5Xue1ztfyNU8KG9jVvn0nnRSkkBhDauek7Y0qOayIeogmKvQLx
      ni8XayjxdvD7p/cjfoZ4FkR8ti+idopqUsH2MIzjfdnx2OKfd2ZmvUAj0DsNdHuM
      LnM37EfGEK6ZIGLipOATHOBIL8odNEFH8ZjWtZYPPVnXAOddxdIgSce8PlZUGohM
      b1ibRmE8vi2Li8/BXuBt6NM1SmSrm6qbDsnIpA1xzL0bW9lJp5zMe0940nPp3G+Q
      nLtRugMqRuJtAfTLGd+K7Cw7cYPDeENIpqtJOgaTNQKBgQD4MaOBr9/nNmQU5Ebi
      s9H5AqC3JUr+Ih2TRBM0ZBUvx3YN/QLJHmqHgYlyOclGA1aT3qDHGqWvOwkYfotC
      /z49BOmqAkUluvQepuszXgDeFj+CaCIocBOSUDZnOQxB7WZEKCvBPGXcsL/vfiiP
      4DiqiUmFdk6yQuIcaYJF/xtOewKBgQDevVIYAwlccYboE6BsHjCPS+M0j318CP3T
      rhwkGeLIgs5YqpIhHYHq4qEjp8hgvb0Mzv+0oglahuRubWqf1fg1SOy1l5iQNc4L
      yEgG7g7gKeNYZwAfZU2Bg3C/2ViKRQwFYcRcFOUI3ixXFaRp0KsU5pIoz1tTzKKF
      T/xB6GA3pwKBgEMr5A2wVM/Vx6Zj1c97TWOwU2Dd5fr7rrdxoCT4xUcmG4xTopJd
      +gTsiQ9yFkgtlRv2D9tzGc5gEukfLn+WZvjKwJazgJVikLlPAa7oTSHOMagQmNYK
      5zEdJmwvY2LgZmIh4R2uQ/9Dkt61bTLrQ0rcVxqY11mlgl6gK5LYJULLAoGAOlQF
      jXguGWE5XMjW97koKj5LL1ZsG/EW1zn+8I0+0BdBBgMU5Use3G2gmP+0/3Bwc0w5
      tgnAvU4Zv7kzdMvJhdqk8iDSuOD+JiO6iOYKSzVs7Zd7dr1GgKX0/qhiAUN3lGk3
      zI1ENQBJSDzIo1UbmAuRNtKmLdmmrZZ2jqPVnn0CgYEA3cw/rRZwnxAYcdqhtcB6
      rVN7XiXTNZ0601kaTaCUh53LNoGYJKj+pBEDws4t+ZPKVaak96qhk8g7CdtYB4ux
      OSwNSb0SM+9ULG1OoDT4kd+BWlbYD5zSnl7W2xhOV8WRHVZByY7TXBObPRyvWHds
      YtX/9tuqApD821wMy2vpKTY=
      -----END PRIVATE KEY-----
    clients:
      - id: who-owes-me
        description: Who Owes Me App
        secret: '$plaintext$secret'
        public: false
        authorization_policy: one_factor
        redirect_uris:
          - http://localhost:8080/callback
        scopes:
          - openid
          - profile
          - email
          - groups
